[install]
linkWorkspacePackages = true

[test]
preload = "./packages/@kimzuni/templify-cli/tests/preload.ts"
coverage = true
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
	"**/tests/**",
	"../**",
]
